version: '3'
services:
  jupyter_lab:
    build:
      context: .
      dockerfile: Dockerfile
    image: anaconda_image
    ports:
    - "8080:8888"
    
    user: 0:0
    environment:
    - JUPYTER_ENABLE_LAB=yes
    - GRANT_SUDO=yes
    
    volumes:
    - .:/workdir
    
    command: start.sh jupyter lab
    
